/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.mojang.escape;

import org.junit.Test;
import static org.junit.Assert.*;

public class EscapeComponentTest {
    @Test public void appHasAGreeting() {
    }
}
